### ISSUE TITLE
Typescript slow 

### ISSUE THREAD

**Issue by mario-amazing** [quangnguyen30192/cmp-nvim-tags#7]
I'm using `cmp-nvim-tags` with `vim-gutentags` and in typescript files(tsx) I have cursor freeze when I'm typing more then 4 symbols.
Source config:
```
  sources = cmp.config.sources({
    { name = 'tags', max_item_count = max_item_count  },
  }),
```

https://user-images.githubusercontent.com/9537753/186727516-f0e12948-5569-4208-bb4e-95b554243751.mov

**Comment by quangnguyen30192** [comment]
Hey @mario-amazing Apologies for the delay, could you send us your config so I can replicate the issue. And how large is your tag file?

**Comment by mario-amazing** [comment]
It's totally ok)))

Conf:
```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/vim-vsnip'
Plug 'hrsh7th/cmp-path'
Plug 'quangnguyen30192/cmp-nvim-tags'

call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
local max_item_count = 4

cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<C-p>'] = cmp.mapping.select_prev_item(),
    ['<C-n>'] = cmp.mapping.select_next_item(),

    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = cmp.config.sources({
    { name = 'tags', max_item_count = max_item_count  },
  }),
}


EOF
```
Last tag:
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/9537753/187275719-924aebad-bc0f-44d7-ae01-79983266a391.png">

**Comment by quangnguyen30192** [comment]
Thank you. I tried with your config and it works fine for me. Your tag file is huge because it tried to scan and generate tags inside node_modules. In the runtime, cmp loads that huge amount tag and it causes delay. Can you try the following suggestion: 

1. Use without vim-gutentags. You actually don't really need it as you can generate tag yourself by ctags https://github.com/universal-ctags/ctags
2. Try to regenerate a tag file that not include node_modules
> ctags -R  --languages=typescript --exclude=.git --exclude=node_modules       
You can find out typescript ctag here https://github.com/jb55/typescript-ctags
3. Open neovim and try with your new tag file.

**Comment by mario-amazing** [comment]
@quangnguyen30192, without node_modules it is totally fine! Thanks a lot!
